1999-2-3: Partied like it was 1999!
Traceback (most recent call last):
  File "dates.py", line 194, in <module>
    main()
  File "dates.py", line 103, in main
    set_dates()
  File "dates.py", line 132, in set_dates
    date_line = format_date(date_line)
  File "dates.py", line 191, in format_date
    assert int(month) <= 12 and int(day) <= 31, "ERROR: Illegal date."
AssertionError: ERROR: Illegal date.
